### ISSUE TITLE
EADN developer number

### ISSUE THREAD

**Issue by mrlucmorin** [Suplanus/Suplanus.Sepla#8]
Hallo Johann,

In one of your files, I can see your EADN dev number. Isn't that something we should keep private?

I must admit that the support I'm getting in Canada for API topics is very poor, and I never could really get hold of KRM to discuss EADN topics in depth.

What I'm told is that anyone with your EADN number can ask EPLAN to add that number to their EID (if they have an API runtime licence).

Is that correct? If so, I thought I'd give you a heads up so that you can hide that information :-)

Regards,

**Comment by Suplanus** [comment]
Thanks for the reply Luc.
It's no problem if there is the EADN number in the code.
Also it would be no problem if the keyfile is in the repo. Because only allowed Company-Logins, can sign the binary at the EPLAN website.

Every customer can buy a runtime of each EADN number. So, yes thats correct :)
